steps:
  checks:
    image: sinontm/ziglang:v1
    commands:
      - zig version
      - zig fmt --check .

  build:
    image: sinontm/ziglang:v1
    commands:
      - zig build demo
      - zig build ray
      - zig build game